"""MCP server exposing BridgeWebs bridge game postmortem data.

Transport: streamable HTTP (endpoint /mcp) on BRIDGEWEBS_POSTMORTEM_MCP_PORT
(default 8514), stateless with JSON responses so plain HTTP clients and
cloudflared work without session affinity. Same pattern as
Bridge_Game_Postmortem_Chatbot/acbl_postmortem_mcp_server.py.

Data source: the parquet cache written by the Streamlit app
(bridgewebs_postmortem_streamlit.py saves each augmented unfiltered game
dataframe to cache/df-{club}-{session}.parquet). This server is a read-only
SQL/report layer over that cache via bridgewebs_postmortem_service; it never
scrapes BridgeWebs or re-runs augmentation. Postmortems are generated by
loading https://bridgewebs.postmortem.chat, entering a BridgeWebs results URL
and selecting a player.

Deployment: bridgewebs-mcp container, started by
../7nt/postmortem_start.ps1. GET /health is used by the wslc watchdog and
deploy health checks.
"""

import os
from typing import Any, Dict, Optional

from mcp.server.mcpserver import MCPServer
from starlette.requests import Request
from starlette.responses import JSONResponse

import bridgewebs_postmortem_service as svc

BRIDGEWEBS_POSTMORTEM_MCP_PORT = int(os.environ.get("BRIDGEWEBS_POSTMORTEM_MCP_PORT", "8514"))

mcp = MCPServer("bridgewebs-postmortem")


@mcp.custom_route("/health", methods=["GET"])
async def health(request: Request) -> JSONResponse:
    """Liveness probe for the wslc watchdog / deploy health check."""
    info = svc.dataset_info()
    return JSONResponse(
        {
            "status": "ok",
            "service": "bridgewebs-mcp",
            "cache_dir": info["cache_dir"],
            "cached_postmortems": info["cached_postmortems"],
        }
    )


@mcp.tool()
def bridgewebs_postmortem_dataset_info() -> Dict[str, Any]:
    """Summary of the BridgeWebs postmortem cache: how many postmortems are
    cached, for which clubs, and how new ones get generated."""
    return svc.dataset_info()


@mcp.tool()
def bridgewebs_postmortem_sessions(club: Optional[str] = None, limit: int = 100) -> Dict[str, Any]:
    """List cached BridgeWebs postmortem sessions (newest first), optionally
    for one club. Each entry has club, session_id (BridgeWebs event id), and
    cache timestamps. A session must appear here before the
    players/boards/sql/schema tools can query it."""
    sessions = svc.list_cached_postmortems(club)[: max(1, min(limit, 500))]
    return {"sessions": sessions, "count": len(sessions)}


@mcp.tool()
def bridgewebs_postmortem_players(
    club: Optional[str] = None,
    session_id: Optional[str] = None,
) -> Dict[str, Any]:
    """Player names appearing in one cached BridgeWebs postmortem (newest
    session when club/session_id are omitted). BridgeWebs identifies players
    by NAME, so use these values as player_name in the boards/sql tools."""
    df, meta = svc.load_postmortem(None, club, session_id)
    names = svc.player_names(df)
    return {"meta": meta, "players": names, "count": len(names)}


@mcp.tool()
def bridgewebs_postmortem_boards(
    player_name: str,
    club: Optional[str] = None,
    session_id: Optional[str] = None,
    only_my_boards: bool = True,
    columns: Optional[str] = None,
    limit: int = 100,
) -> Dict[str, Any]:
    """Per-board results for one cached BridgeWebs postmortem, personalized
    for a player (by name; discover names with bridgewebs_postmortem_players):
    contract, declarer, result, tricks, scores, matchpoint percentages, and
    the deal (PBN).

    club/session_id: omit for the most recently cached game.
    only_my_boards: True (default) limits rows to boards the player's pair
    actually played; False returns every board in the game (all pairs).
    columns: optional comma-separated column names to override the default
    summary set (discover names with bridgewebs_postmortem_schema).
    """
    df, meta = svc.load_postmortem(player_name, club, session_id)
    cols = [c.strip() for c in columns.split(",")] if columns else None
    return svc.board_results(df, meta, only_my_boards=only_my_boards, columns=cols, limit=limit)


@mcp.tool()
def bridgewebs_postmortem_sql(
    player_name: str,
    sql: str,
    club: Optional[str] = None,
    session_id: Optional[str] = None,
    limit: int = svc.DEFAULT_SQL_ROW_LIMIT,
) -> Dict[str, Any]:
    """Run a DuckDB SQL query against one cached BridgeWebs postmortem,
    registered as table 'self' (one row per board result, thousands of
    augmented columns: double-dummy, par, single-dummy expected values, HCP,
    ...), personalized for a player (by name).

    'FROM self' is prepended when the query does not reference it, so both
    'SELECT ... FROM self ...' and DuckDB's 'SELECT ...' shorthand work.
    Personalization macros are substituted before execution:
    {Player_Direction}, {Partner_Direction}, {Pair_Direction},
    {Opponent_Pair_Direction}. Boolean helper columns include Boards_I_Played,
    Boards_I_Declared, Boards_We_Declared, Boards_Opponent_Declared.
    club/session_id: omit for the most recently cached game.
    """
    df, meta = svc.load_postmortem(player_name, club, session_id)
    result = svc.run_sql(df, sql, meta, limit=limit)
    result["meta"] = meta
    return result


@mcp.tool()
def bridgewebs_postmortem_schema(
    club: Optional[str] = None,
    session_id: Optional[str] = None,
    pattern: Optional[str] = None,
    limit: int = 200,
) -> Dict[str, Any]:
    """Column names and dtypes of one cached BridgeWebs postmortem dataframe.
    The frame has thousands of augmented columns, so pass a case-insensitive
    regex pattern (e.g. 'Pct|Score', '^DD_', 'PairId') to search for relevant
    ones before writing bridgewebs_postmortem_sql queries."""
    df, _ = svc.load_postmortem(None, club, session_id)
    return svc.schema_columns(df, pattern=pattern, limit=limit)


if __name__ == "__main__":
    print(
        f"[bridgewebs-mcp] starting on :{BRIDGEWEBS_POSTMORTEM_MCP_PORT} "
        f"(endpoint /mcp, health /health); cache -> {svc.CACHE_DIR}",
        flush=True,
    )
    # Stateless + JSON responses: plain request/response tools, no session
    # affinity needed behind cloudflared, and curl-testable.
    mcp.run(
        transport="streamable-http",
        host="0.0.0.0",
        port=BRIDGEWEBS_POSTMORTEM_MCP_PORT,
        stateless_http=True,
        json_response=True,
    )
